include_recipe 'java::default'
# include_recipe 'scala::default'
# include_recipe 'groovy::default'
# include_recipe 'gradle::default'
# include_recipe 'idea::default'
include_recipe 'postgresql::server'
